### ISSUE TITLE
On the unending journey of finding something better than Common Lisp

### ISSUE THREAD

**Issue by xieyuheng** [Silverbeard00/RILEY#14]
On the unending journey of finding something better than Common Lisp,
I found javascript and typescript.

**Comment by ArnautDaniel** [comment]
I'm not falling for the bait :P

**Comment by xieyuheng** [comment]
sexp has problem : https://github.com/xieyuheng/cicada-rs/blob/master/mexp/README.md#the-rigid-body-indentation-problem

as for macro system, js babel (extend syntax by compiler plugins)
https://babeljs.io/
can extend the syntex of `.js` to `.ts` and `.jsx`, even `.vue`
feels like the king of syntax extension.

**Comment by xieyuheng** [comment]
rust has three level of syntax extensions,
1. something like scheme pattern matching macro
2. something like lisp low level macro
3. compiler plugin

library and framework writers always use compiler plugin
designed some nice programming interface like this https://rocket.rs/

**Comment by xieyuheng** [comment]
alas scheme and lisp ~
I wish I can find a job using scheme and lisp

nevermind ~
I am drunk >_<

**Comment by ArnautDaniel** [comment]
Your Sexp example is a non issue.  Rigid indentation is nice.  Sexp are entirely consistent and follow the principle of least astonishment.  

Also when did rust come into this?  Rust is even worse than JavaScript.
